### ISSUE TITLE
[name].min.[extension]

### ISSUE THREAD

**Issue by alessandrotraversi** [wykapedia/brackets-clientlibs-combine#2]
Hi, thanks for your project!
I think that brackets-clientlibs-combine is a simple and great plugin.

I try to write this (like brackets concat plugin) in my clientlibs.combine, but obviusly doesn't works:

{
    "combineOnSave": true,
    "minify":true,
    "combine": [
        {
            "output": "public/js/home.min.js",
            "files": [
                "resources/assets/script/component/layout.js",
                "resources/assets/script/page/contact.js"
            ]
        }
}

Is there some way to minify automatically the output?

**Comment by wykapedia** [comment]
Currently there is no support for minification of output files.  Please feel free to extend this plugin and create the feature yourself.

**Comment by Daminoweb** [comment]
Would be great to add this feature : minify and combine in one operation.

Thanks.
