### ISSUE TITLE
Not working on my Brackets 1.6 ?

### ISSUE THREAD

**Issue by Daminoweb** [wykapedia/brackets-clientlibs-combine#3]
Hello and thanks for the plugin.
I was using concat Brackets CSS concat and Brackets JS concat, but was looking for just one plugin to combine CSS and JS files. That's why I install your plugin.
Unfortunately the plugin doesn't work on my 1.6 Brackets. Is there any things I haven't understood ?

I create a clientlibs.combile file in my root directory and fill it with :

```
{
    "combineOnSave": false,
    "combine": [
        {
            "output": "combine/css/styles.min.css",
            "files": [
                "style1.css",
                "style2.css"
            ]
        },
        {
            "output": "combine/js/perso.min.js",
            "files": [
                "jstest/*.js"
            ]
        },
    ]
}
```

But when I right-click on the file and click Combine client Libs, nothing happens.

Thanks for your help.

**Comment by wykapedia** [comment]
I have tested on Brackets 1.6 and it is working for me.  Do you see any errors in the console?

**Comment by Daminoweb** [comment]
Hi and thanks for your answer.
I'm not a good dev enough to explore errors but ...
The only error I have when I launch Combine Client Libs is : 
`Uncaught SyntaxError: Unexpected token ]`

**Comment by Daminoweb** [comment]
Hi again I've disable some extensions and it's OK.
I'm triyng to find the one responsable for that error.

**Comment by Daminoweb** [comment]
Last test.
No problem of extensions, it was just a problem of coma.
Here is the code OK

```
{
    "combineOnSave": false,
    "combine": [
        {
            "output": "combine/css/styles.min.css",
            "files": [
                "style1.css",
                "style2.css"
            ]
        },
        {
            "output": "combine/js/perso.min.js",
            "files": [
                "jstest/*.js"
            ]
        }
    ]
}
```

```
```

**Comment by wykapedia** [comment]
Good find.
