### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Daminoweb** [wykapedia/brackets-clientlibs-combine#4]
Hi, hope you're still here.
I used to use this extension. I didn't use again for several monthes and now it's not working. I even can't have some menu when I click right.
Do you have an idea ? may be something I didn't understand.
-I've tried to deactivate all other extensions with no success
-I have a file called clientsLibs.combine whith
`{
    "combineOnSave": false,
    "combine": [
        {
            "output": "assets/styles.min.css",
            "files": [
                "assets/style.min.css",
                "assets/skills.min.css"
            ]
        }  
    ]
}`
(I'm using Brackets 1.8)

Thanks.

**Comment by wykapedia** [comment]
This has been fixed with https://github.com/wykapedia/brackets-clientlibs-combine/releases/tag/v0.0.3

**Comment by Daminoweb** [comment]
Thanks !
